import random as rd

def randomIntegerNumber(a,b):
    numb = rd.randint(a,b)
    return numb

def randomFloatingNumber(a,b,c):
    numb = rd.uniform(a,b)
    numbr = round(numb,c)
    return numbr

def difference(a,b):
    if(a>b):
        print("You guessed wrong by ",(a-b))
    else:
        print("You guessed wrong by ",(b-a))


print("This is a guessing game, you should provide the range of number between which you should guess.")
print("If you want to guess integers then enter 1. If you want to guess for decimal numbers, press 2")
print()
y = int(input("Enter 1 for intergers | 2 for decimals: "))
if(y==1):
    a = int(input("Enter the starting number: "))
    b = int(input("Enter the ending number: "))
    c = int(input("Enter your guess: "))
    ans = randomIntegerNumber(a,b)
    print("Number generated by machine: "+str(ans))
    if(c==ans):
        print("You guessed it write")
    else:
        difference(c,ans)

else:
    a = float(input("Enter the starting decimal number: "))
    b = float(input("Enter the ending decimal number: "))
    c = int(input("Enter the number of decimal places for display: "))
    d = float(input("Enter your guess: "))
    ans = randomFloatingNumber(a,b,c)
    print("Number generated by machine: "+str(ans))
    if(d==ans):
        print("You guessed it write")
    else:
        difference(d,ans)